### ISSUE TITLE
Rename app.js to be more descriptive

### ISSUE THREAD

**Issue by elipalmer** [HarperDB/HarperDB_Studio#13]
app.js is the default name for new Node projects, it could be renamed to be more descriptive.  hdb_studio.js seems like a reasonable name but should be discussed.

Exit Criteria:
1.  The app should start with no errors by referencing the new name.
2.  The README file instructions should be updated.

**Comment by tdreid** [comment]
How descriptive vs. terse would you want it:

- studio.js
- dbstudio.js
- harper-db-studio.js

etc?

**Comment by tdreid** [comment]
Oops, I see the answer is already there.

**Comment by elipalmer** [comment]
Merged, thanks again for your time @tdreid!
