### ISSUE TITLE
After failed login attempt Login form fields are 'undefined'

### ISSUE THREAD

**Issue by tdreid** [HarperDB/HarperDB_Studio#26]
**Describe the bug**
When a user's login attempt in not successful the 'Endpoint URL' and 'Endpoint Port' field will contain 'undefined' upon return to the login form.  It should preserve the user's entry instead.

**To Reproduce**
1. Go to the login page
2. Enter an a username with the wrong password.
3. Enter a valid endpoint url and a valid endpoint port
3. Click the 'Login' button
4. The field 'Endpoint URL' and 'Endpoint Port' fields will contain the string 'undefined'

![image](https://user-images.githubusercontent.com/868675/41208829-df821a2e-6cf4-11e8-941a-3ba1e2f23540.png)

**Expected behavior**
Whatever the user entered should be preserved in non-password fields. 

**Environment:**
 - OS: Windows 7 and Windows 10
 - Browser: Chrome
 - Version 67.0.3396.79 (Official Build) (32-bit)

**Comment by elipalmer** [comment]
@tdreid  thanks for bringing this up.  I'm closing in favor of Issue #21, only because it was created earlier.
