### ISSUE TITLE
The studio fails to start and incorrectly says HarperDB Studio requires Node.js version 8.11 or higher

### ISSUE THREAD

**Issue by kylebernhardy** [HarperDB/HarperDB_Studio#30]
**Describe the bug**
If you are on Node.js v 10.X or higher and start the studio you will receive the message: "HarperDB Studio requires Node.js version 8.11 or higher"

**To Reproduce**
1. Install Node.js v 10.X or higher
2. Start the studio
3. The error: "HarperDB Studio requires Node.js version 8.11 or higher" is sent to the console and the studio refuses to start

**Expected behavior**
The expected behavior is for the Studio to start

**Comment by Ethan-Arrowood** [comment]
Should this be closed per https://github.com/HarperDB/HarperDB_Studio/pull/31 ?

**Comment by Ethan-Arrowood** [comment]
Closing with #31
