### ISSUE TITLE
Incorrect spelling in Schema detail page

### ISSUE THREAD

**Issue by elipalmer** [HarperDB/HarperDB_Studio#39]
**Describe the bug**
Schema is spelled Scema in the schema detail page

**To Reproduce**
1. Start HarperDB
2. Start the studio
3. Browse to http://localhost:8080/schema/
4. Select a schema
5. See incorrect spelling in the corner

**Expected behavior**
Should be spelled 'Schema'

**Screenshots**

![image](https://user-images.githubusercontent.com/3770524/42956442-31d91cc6-8b3d-11e8-9a74-a31be0db240b.png)

**Comment by Alyssa-Cooper** [comment]
I'll take this

**Comment by ShawnToubeau** [comment]
This seems to have been fixed already.
